name: 'CI Builds'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  check-maven:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        javaVersion: [ 8, 21 ]
        javaDist: [ temurin ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: test-${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            test-${{ matrix.os }}-maven-
      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: ${{ matrix.javaDist }}
      - name: 'Check Spock'
        run: |
          mvn -V -B verify
